services:
  app:
    build: .
    image: thespagi/test-app-v2:latest
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432