name: CI - Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build_format_test:
    uses: ./.github/workflows/ci-build-format-test.yml
    secrets: inherit

  containerize-and-push:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Create .env file
          run: |
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} > .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env

        - name: Build and push Docker image
          run: |
            docker-compose build
            docker-compose push