name: CI - Release

on:
  push:
    branches:
      - release

jobs:
  build_format_test:
    uses: ./.github/workflows/ci-build-format-test.yml
    secrets: inherit

  containerize:
    uses: ./.github/workflows/containerize.yml
    secrets: inherit
    needs: build_format_test
