name: CI - Validate

on:
  push: 
    branches:
      - feature/*
      - dev
  pull_request:
    branches:
      - dev
      - release/*

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/format.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  