name: CI - Validate

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  format:
    uses: ./.github/workflows/format.yml

  test:
    uses: ./.github/workflows/test.yml  