name: CI - Validate

on:
  push: 
    branches:
      - feature/*
      - dev
  pull_request:
    branches:
      - dev
      - release/*

jobs:
  validate:
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Format 
        uses: ./.github/workflows/format.yml

      - name: Test 
        uses: ./.github/workflows/test.yml
