name: CI - Validate

on:
  push: 
    branches:
      - feature/*
      - dev
  pull_request:
    branches:
      - dev
      - release/*

jobs:
  validate:
    uses: ./.github/workflows/build.yml
    uses: ./.github/workflows/format.yml
    uses: ./.github/workflows/test.yml
