name: Deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy Docker Compose file to DigitalOcean droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        source: docker-compose.yml
        target: /root/app

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        script: |
          cd /root/app
          docker compose pull
          docker compose up -d